image: docker:20.10.16

services:
  - docker:20.10.16-dind

# Stages, which define when to run the jobs. For example, stages that run tests after stages that compile the code.
stages:
  - Deploy

deploy:
  stage: Deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t gitlab.lrz.de:5005/ase-22-23/team04/frontend/ase-delivery-portal .
    - docker push gitlab.lrz.de:5005/ase-22-23/team04/frontend/ase-delivery-portal
  only:
    refs:
      - main
